version: '3'

services:

  user_management:
    build: ./srcs/user_management
    container_name: user_management
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./srcs/user_management/app:/usr/src/app
      - ./srcs/is_ready:/is_ready
    networks:
      - net
    depends_on:
      - db_nginx

  db_nginx:
    build: 
      context: ./srcs/db_nginx
      args:
        CRT_PATH: ${PATH_CRT}
    container_name: db_nginx
    ports:
      - "443:443"
      - "8080:80"
    env_file:
      - .env
    networks:
      - net
    volumes:
      - ./srcs/is_ready:/is_ready
      - ./srcs/db_nginx/front-end:/usr/share/nginx/html
    

networks:
  net: