FROM    python:3.10

# RUN apt update && apt install -y curl
COPY    game/requirements.txt .

RUN     pip install -r requirements.txt

COPY    certs certs
COPY    game/script/script.sh .

CMD ["bash","script.sh"]