# Generated by Django 5.0.7 on 2024-09-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/unknown.jpg', max_length=255, upload_to='profile_images/'),
        ),
    ]
