# Generated by Django 5.0.7 on 2024-07-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
