# Generated by Django 5.0.7 on 2024-09-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, default='https://localhost:8000/home/profile_images/unkown.jpj', max_length=255),
        ),
    ]
