# Generated by Django 5.0.7 on 2024-09-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_chat_table_alter_contact_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
    ]
