# Generated by Django 5.0.7 on 2024-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, default='https://localhost/home/profile_images/unkown.jpg', max_length=255),
        ),
    ]
