# Generated by Django 5.0.6 on 2024-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_aiscore_alter_game_playerscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ballVX',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='ballVY',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='ballX',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='game',
            name='ballY',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='game',
            name='canvasHeight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='canvasWidth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='paddle1X',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='paddle1Y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='game',
            name='paddle2X',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='game',
            name='paddle2Y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='game',
            name='paddleLen',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='game',
            name='velocity',
            field=models.IntegerField(default=6),
        ),
    ]
