# Generated by Django 5.0.6 on 2024-06-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_ballvx_game_ballvy_game_ballx_game_bally_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ballVX',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ballVY',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ballX',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ballY',
        ),
        migrations.RemoveField(
            model_name='game',
            name='canvasHeight',
        ),
        migrations.RemoveField(
            model_name='game',
            name='canvasWidth',
        ),
        migrations.RemoveField(
            model_name='game',
            name='over',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddle1X',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddle1Y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddle2X',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddle2Y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='paddleLen',
        ),
        migrations.RemoveField(
            model_name='game',
            name='velocity',
        ),
    ]
