# Generated by Django 5.0.6 on 2024-06-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_ballvx_remove_game_ballvy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isOver',
            field=models.BooleanField(default=False),
        ),
    ]
