# Generated by Django 5.0.6 on 2024-07-04 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_isover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='aiScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='playerScore',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MultiGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player2Score', models.IntegerField(default=0)),
                ('player1Score', models.IntegerField(default=0)),
                ('isOver', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='multiPlayerGames1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='multiPlayerGames2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wonGames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
