# Generated by Django 5.0.6 on 2024-07-06 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_aiscore_alter_game_playerscore_multigame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multigame',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='multigame',
            name='player2',
        ),
        migrations.AddField(
            model_name='multigame',
            name='players',
            field=models.ManyToManyField(related_name='multiPlayerGames', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multigame',
            name='room_name',
            field=models.TextField(default=''),
        ),
    ]
