# Generated by Django 5.0.6 on 2024-07-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_multigame_player1_remove_multigame_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
