FROM python:3.10

WORKDIR /app 

COPY chat/requirements.txt .

RUN pip install --upgrade pip --root-user-action=ignore && pip  install -r requirements.txt --root-user-action=ignore

COPY chat/src /app/

COPY    certs certs

COPY chat/script/runchat.sh .

RUN chmod 777 runchat.sh

CMD ["./runchat.sh"]