# FROM python:3.10

# ENV PYTHONUNBUFFERED 1
# ENV PIPENV_VENV_IN_PROJECT 1

# WORKDIR /app

# COPY Pipfile Pipfile.lock /app/

# RUN pip install pipenv

# RUN pipenv install --ignore-pipfile

# COPY src /app/


# CMD ["pipenv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]


FROM python:3.10

WORKDIR /app 

COPY chat/requirements.txt .

RUN pip install --upgrade pip --root-user-action=ignore && pip  install -r requirements.txt --root-user-action=ignore

# RUN apt-get update && apt-get install -y redis-server

COPY chat/src /app/

COPY    certs certs

COPY chat/script/runchat.sh .

RUN chmod 777 runchat.sh

CMD ["./runchat.sh"]
